=== Dusk1706/school-projects/Tesebada/unidad4/proyecto1/empresa.dtd
<!ELEMENT empresa (personas, almacen, ordenes)>

<!ELEMENT ordenes (orden+)>
<!ELEMENT orden (fecha, orden_detalles)>
<!ATTLIST orden codigo ID #REQUIRED>
<!ATTLIST orden cliente IDREF #REQUIRED>
<!ATTLIST orden empleado IDREF #REQUIRED>

<!ELEMENT orden_detalles (orden_detalle+)>
<!ELEMENT orden_detalle (cantidad, precio_unitario)>
<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST orden_detalle orden IDREF #REQUIRED>
<!ATTLIST orden_detalle producto IDREF #REQUIRED>

<!ELEMENT personas (empleados, clientes, proveedores, transportistas)>

<!ELEMENT transportistas (transportista+)>
<!ELEMENT transportista (nombre_empresa, (contacto | contactos))>
<!ATTLIST transportista codigo ID #REQUIRED>

<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre, titulo, fecha_nacimiento, fecha_contratacion, direccion, telefono)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha_nacimiento (fecha)>
<!ELEMENT fecha_contratacion (fecha)>
<!ATTLIST empleado codigo ID #REQUIRED>
<!ATTLIST empleado jefe IDREF #IMPLIED>

<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombre, fecha_nacimiento, direccion, telefono, correo?)>
<!ATTLIST cliente codigo ID #REQUIRED>

<!ELEMENT proveedores (proveedor+)>
<!ELEMENT proveedor (nombre_empresa, (contacto | contactos), correo?)>
<!ATTLIST proveedor codigo ID #REQUIRED>

<!ELEMENT almacen (categorias, productos)>

<!ELEMENT productos (producto+)>
<!ELEMENT producto (nombre, precio_unitario)>
<!ATTLIST producto codigo ID #REQUIRED>
<!ATTLIST producto proveedor IDREF #REQUIRED>
<!ATTLIST producto categoria IDREF #REQUIRED>

<!ELEMENT categorias (categoria+)>
<!ELEMENT categoria (nombre, descripcion?)>
<!ATTLIST categoria codigo ID #REQUIRED>

<!ELEMENT fecha (dia, mes, año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT nombre_empresa (#PCDATA)>
<!ELEMENT precio_unitario (#PCDATA)>
<!ELEMENT contactos (contacto+)>
<!ELEMENT contacto (nombre, telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

=== Dusk1706/school-projects/Tesebada/unidad4/proyecto1/empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "empresa.dtd">
<empresa>
    <personas>
        <empleados>
            <empleado codigo = "empleado1">
                <nombre>Luis Daniel Coppel Garcia</nombre>
                <titulo>Ing. Mecanica</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>29</dia>
                        <mes>09</mes>
                        <año>2002</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>31</dia>
                        <mes>10</mes>
                        <año>2003</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 37, Colonia 14, Ciudad 43</direccion>
                <telefono>5628413391</telefono>
            </empleado>
            <empleado codigo = "empleado2" jefe = "empleado1">
                <nombre>Javier Luis Perez Lopez</nombre>
                <titulo>Ing. Mecanica</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>19</dia>
                        <mes>12</mes>
                        <año>2012</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>09</dia>
                        <mes>01</mes>
                        <año>2023</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 5, Colonia 60, Ciudad 20</direccion>
                <telefono>3855377745</telefono>
            </empleado>
            <empleado codigo = "empleado3" jefe = "empleado2">
                <nombre>Carolina Sofia Diaz Perez</nombre>
                <titulo>Ing. Industrial</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>30</dia>
                        <mes>04</mes>
                        <año>2018</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>06</dia>
                        <mes>05</mes>
                        <año>2005</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 56, Colonia 13, Ciudad 18</direccion>
                <telefono>8505933201</telefono>
            </empleado>
            <empleado codigo = "empleado4" jefe = "empleado2">
                <nombre>Sofia Zoila Lopez Diaz</nombre>
                <titulo>Ing. Sistemas</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>03</dia>
                        <mes>09</mes>
                        <año>2014</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>05</dia>
                        <mes>06</mes>
                        <año>2001</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 78, Colonia 26, Ciudad 92</direccion>
                <telefono>2542061302</telefono>
            </empleado>
            <empleado codigo = "empleado5">
                <nombre>Carolina Yessenia Diaz Lopez</nombre>
                <titulo>Ing. Electrico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>13</dia>
                        <mes>10</mes>
                        <año>2024</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>02</dia>
                        <mes>10</mes>
                        <año>2001</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 20, Colonia 55, Ciudad 68</direccion>
                <telefono>2804788276</telefono>
            </empleado>
            <empleado codigo = "empleado6">
                <nombre>Anastacia Maria Urias Urias</nombre>
                <titulo>Ing. Electrico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>17</dia>
                        <mes>07</mes>
                        <año>2006</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>31</dia>
                        <mes>12</mes>
                        <año>2015</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 19, Colonia 71, Ciudad 9</direccion>
                <telefono>6413795774</telefono>
            </empleado>
            <empleado codigo = "empleado7" jefe = "empleado3">
                <nombre>Rebeca Nereida Perez Lopez</nombre>
                <titulo>Ing. Electrico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>28</dia>
                        <mes>03</mes>
                        <año>2011</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>07</dia>
                        <mes>07</mes>
                        <año>2000</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 52, Colonia 77, Ciudad 7</direccion>
                <telefono>7040721593</telefono>
            </empleado>
            <empleado codigo = "empleado8">
                <nombre>Sofia Carolina Diaz Urias</nombre>
                <titulo>Ing. Bioquimico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>21</dia>
                        <mes>01</mes>
                        <año>2013</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>08</dia>
                        <mes>04</mes>
                        <año>2004</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 33, Colonia 61, Ciudad 76</direccion>
                <telefono>1672762520</telefono>
            </empleado>
            <empleado codigo = "empleado9" jefe = "empleado5">
                <nombre>Yessenia Anastacia Coppel Mendoza</nombre>
                <titulo>Ing. Bioquimico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>23</dia>
                        <mes>07</mes>
                        <año>2018</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>29</dia>
                        <mes>04</mes>
                        <año>2008</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 18, Colonia 100, Ciudad 56</direccion>
                <telefono>2045206930</telefono>
            </empleado>
            <empleado codigo = "empleado10" jefe = "empleado3">
                <nombre>Maria Zoila Perez Lopez</nombre>
                <titulo>Ing. Electrico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>08</dia>
                        <mes>09</mes>
                        <año>2024</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>26</dia>
                        <mes>06</mes>
                        <año>2016</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 41, Colonia 60, Ciudad 51</direccion>
                <telefono>9619084617</telefono>
            </empleado>
            <empleado codigo = "empleado11">
                <nombre>Anastacia Alicia Coppel Diaz</nombre>
                <titulo>Ing. Bioquimico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>09</dia>
                        <mes>08</mes>
                        <año>2014</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>19</dia>
                        <mes>02</mes>
                        <año>2009</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 28, Colonia 89, Ciudad 77</direccion>
                <telefono>5283384310</telefono>
            </empleado>
            <empleado codigo = "empleado12" jefe = "empleado8">
                <nombre>Zoila Yessenia Mendoza Urias</nombre>
                <titulo>Ing. Civil</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>03</dia>
                        <mes>10</mes>
                        <año>2001</año>
                    </fecha>
                </fecha_nacimiento>
                <fecha_contratacion>
                    <fecha>
                        <dia>15</dia>
                        <mes>10</mes>
                        <año>2012</año>
                    </fecha>
                </fecha_contratacion>
                <direccion>Calle 37, Colonia 24, Ciudad 39</direccion>
                <telefono>5904241845</telefono>
            </empleado>
            <empleado codigo = "empleado13" jefe = "empleado11">
                <nombre>Rebeca Yessenia Garcia Perez</nombre>
                <titulo>Ing. Bioquimico</titulo>
                <fecha_nacimiento>
                    <fecha>
                        <dia>10</dia>
